"""create table

Revision ID: 13b632d5b1d6
Revises: 
Create Date: 2024-09-08 12:12:27.644701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13b632d5b1d6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('dateCad', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('dateUp', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('cep', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('complement', sa.String(), nullable=False),
    sa.Column('uf', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('dateCad', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('dateUp', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sale', sa.String(), nullable=False),
    sa.Column('tipe', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('dateCad', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('dateShooting', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gallery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('amount', sa.String(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('dateCad', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('dateUp', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('dateCad', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('dateUp', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.String(), nullable=False),
    sa.Column('id_product', sa.String(), nullable=False),
    sa.Column('amount', sa.String(), nullable=False),
    sa.Column('priceUnit', sa.String(), nullable=False),
    sa.Column('priceFull', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('amountTipe', sa.String(), nullable=False),
    sa.Column('pix_qrcode', sa.String(), nullable=False),
    sa.Column('pix_copia', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('returnPag', sa.String(), nullable=False),
    sa.Column('dateCad', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('dateUp', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shorts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('dateCad', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('dateUp', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shorts')
    op.drop_table('sale')
    op.drop_table('profile')
    op.drop_table('product')
    op.drop_table('gallery')
    op.drop_table('email')
    op.drop_table('client')
    op.drop_table('characters')
    # ### end Alembic commands ###
